apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      name: ftp
      port: 3306
      targetPort: 3306
  type: LoadBalancer