apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    name: nginx-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx-depl
  template:
    metadata:
      labels:
        name: nginx-depl
    spec:
      containers:
      - name: nginx-c
        image: nginx-yslati
        imagePullPolicy: Never
        ports:
        - containerPort: 80
    